### ISSUE TITLE
cannot extract "[[Image:Over 20K.jpg|thumb|慶賀中文版維基突破兩萬條]]" pattern

### ISSUE THREAD

**Issue by t0-0** [floatingbigcat/mm_builder#14]
[this file](https://github.com/floatingbigcat/mm_builder/blob/master/py_workers/wiki2itl.py) cannot extract "[[Image:Over 20K.jpg|thumb|慶賀中文版維基突破兩萬條]]" pattern

**Comment by t0-0** [comment]
also cannot extract "[[:图像:Bian4.png]]" pattern

**Comment by floatingsun** [comment]
Thanks! I think we just need to add more pattern.
pattern = r'\[\[:?(?:ファイル|画像|File|图像|Image):(.*?)(?:\||\]\])'

**Comment by floatingsun** [comment]
pls check this pr
https://github.com/floatingbigcat/mm_builder/pull/15
