### ISSUE TITLE
Add support for chinese wiki

### ISSUE THREAD

**Issue by floatingsun** [floatingbigcat/mm_builder#2]
We only need to do two things to support other languages like chinese
- add zh_parttern for image name regonization
- add basename(prefix) of image url for zh images storage

**Comment by t0-0** [comment]
add zh_pattern for the following image name

- `&lt;li&gt;02:43 2004年3月31日 [[User:Tomchiukc|Tomchiukc]] 已删除"保加利亚" &lt;em&gt;(内容为： &amp;#39;&amp;#91;&amp;#91;Image:Xinsrc 0d920d75668411d6b5ce00b0d03f0b06.gif ]]&amp;#91;&amp;#91;Image:Image:Xinsrc 0d920d75668411d6b5ce00b0d03f0b06.gif ]]&amp;#91;&amp;#91;Image:Xinsrc_f68db8e9667811d6b5ce0...&amp;#39;)&lt;/em&gt;&lt;/li&gt;`
- `[[Image:ACTH Negative Feedback.svg|right|thumb|250px|許多[[內分泌系統]]中的[[荷爾蒙]]都是由負反饋系統所控制，例如[[腎上腺]]分泌的[[糖皮質激素]]就是如此。[[下視丘]]分泌促肾上腺皮质素释放素(CRH)，CRH會使[[腦下垂體]]分泌[[促腎上腺皮質素]](ACTH)，而ACTH會使腎上腺分泌糖皮質激素，如[[皮質醇]]。糖皮質激素不但會使身體有對應的反應外，也會使下視丘和腦下垂體的分泌減少，因此只要糖皮質激素已經到達一定的量，就不會再繼續分泌。&lt;ref&gt;Raven, PH; Johnson, GB. ''Biology'', Fifth Edition, Boston: Hill Companies, Inc. 1999. page 1058.&lt;/ref&gt;]]`
  - the real url for this pattern is https://upload.wikimedia.org/wikipedia/commons/0/0c/ACTH_Negative_Feedback.svg
- `&lt;li&gt;04:50 2004年3月1日 [[User:Shizhao|Shizhao]] 已删除"Image:Sun.jpg"&lt;/li&gt;`

**Comment by floatingsun** [comment]
we don't need to consider the first and thrid example, which are history record. We only need to add zh_pattern for the second example that following the patterns: start with **[[Image:** and end with **|**, similiar to the ja
>>[[Image:ACTH Negative Feedback.svg|right|thumb|250px|許多[[內分泌系統]]中的[[荷爾蒙]]都是由負反饋系統所控制，例如[[腎上腺]]分泌的[[糖皮質激素]]就是如此。[[下視丘]]分泌促肾上腺皮质素释放素(CRH)，CRH會使[[腦下垂體]]分泌[[促腎上腺皮質素]](ACTH)，而ACTH會使腎上腺分泌糖皮質激素，如[[皮質醇]]。糖皮質激素不但會使身體有對應的反應外，也會使下視丘和腦下垂體的分泌減少，因此只要糖皮質激素已經到達一定的量，就不會再繼續分泌。&lt;ref&gt;Raven, PH; Johnson, GB. ''Biology'', Fifth Edition, Boston: Hill Companies, Inc. 1999. page 1058.&lt;/ref&gt;]]

**Comment by floatingsun** [comment]
maybe you can also add the zh url lists, like this one
https://github.com/floatingbigcat/mm_builder/blob/master/data/en_urls.txt

**Comment by floatingsun** [comment]
I think the zh should work now.
