### ISSUE TITLE
Cannot extract [[:画像:埼玉県・縮小版.png]] pattern

### ISSUE THREAD

**Issue by t0-0** [floatingbigcat/mm_builder#4]
[this file(https://github.com/floatingbigcat/mm_builder/blob/master/py_workers/wiki2itl.py)](https://github.com/floatingbigcat/mm_builder/blob/master/py_workers/wiki2itl.py) cannot recognize "[[:画像:埼玉県・縮小版.png]]" pattern.

**Comment by floatingsun** [comment]
It seems that the file you're using is from your forked repo
Could u pls create branch under this repo and try again? as you should have the access.

**Comment by floatingsun** [comment]
Current patterns for ja are
```
\[\[:(?:ファイル|画像):(.*?)\|',    and   \[\[(?:ファイル|画像):(.*?)\|' 
```
they will search for those text **starting with [[ and end with |,**  
eg: 
\n[[ファイル:Ravenet-Mestizos.jpg|左|サムネイル|フアン・ラヴェネット（[[:en:Juan_Ravenet|en]]）作『マニラのメスティーソたち』。18世紀フィリピンの女性は市松模様（パレス）の細身のロングスカート（サヤ）を履いている。男性はヨーロッパ風の服装。（1792頃-1794頃）]]

therefore, the [[:画像:埼玉県・縮小版.png]] will not be found as it end with ]]

**Comment by floatingsun** [comment]
#5

**Comment by t0-0** [comment]
I finally understand why "]]" is not included. However, I could consider both "|" and "]" in the following letter options as some of them do not have "|" and only have "[[...]]".
For example, r'\[\[:(?:ファイル|画像):(.*?)(?:\]|\|)'
